admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
static_resources:
  clusters:
    - name: backend
      type: STATIC
      connect_timeout: 1s
      lb_policy: ROUND_ROBIN
      common_http_protocol_options:
        idle_timeout: 60s
      http2_protocol_options: {}
      load_assignment:
        cluster_name: backend
        endpoints:
          lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 10081
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 10082
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 10083
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 10084
            - endpoint:
                address:
                  socket_address:
                    address: 127.0.0.1
                    port_value: 10085
  listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 10080
      connection_balance_config:
        exact_balance: {}
      filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: backend
              codec_type: AUTO
              route_config:
                name: local_route
                virtual_hosts:
                  - name: backend
                    domains:
                      - "*"
                    routes:
                      - match:
                         prefix: /
                        route:
                          cluster: backend
              http_filters:
                - name: envoy.filters.http.router
                  typed_config: {}
